### ISSUE TITLE
mfxdecode / mfxh264dec h.264 on seek doesn't work

### ISSUE THREAD

**Issue by ashimpd** [01org/gstreamer-media-SDK#5] opened 2017-04-20 11:12 UTC
mfxdecode of h.264 stream after seek gives error "More data". The pipeline works fine if we use avdec_h264, so we don't suspect any issue with pipeline.

**Comment by ishmael1985** [comment] 2017-04-20 15:13
Can you provide a link to the video clip that reproduces this issue?

**Comment by ashimpd** [comment] 2017-04-21 08:07
attached one video file
[test1-480x270.flv.zip](https://github.com/01org/gstreamer-media-SDK/files/946396/test1-480x270.flv.zip)

**Comment by ishmael1985** [comment] 2017-04-21 15:44
I couldn't reproduce the issue with the test clip you provided. I used gst-play-1.0, gtk-play and totem to seek the video, but seeking seems to work pretty well for me. Are you seeking with a custom GStreamer app you've written?

**Comment by ashimpd** [comment] 2017-04-21 15:55
Yes. It's a custom App. However, when I replace mfxdecode with avdec_h264 in the pipeline, seek works.

**Comment by SiewHoon** [comment] 2017-08-01 00:43
I will close this issue. If the issue still exist, feel free to submit the issue again.

**Closed by SiewHoon** 2017-08-01 00:43 UTC
